name: Idenmoji Build

on:
  push:
    paths:
      - 'Makefile'
      - 'identmoji.c'
    branches:
      - main
  pull_request:
    paths:
      - 'Makefile'
      - 'identmoji.c'
    branches:
      - main
  workflow_dispatch: # Allow manually triggering the workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4

    # Step 2: Install dependencies
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev

    # Step 3: Compile the binary using Makefile
    - name: Build with make
      run: make

    # Step 4: Run a basic test
    - name: Test the binary
      run: ./identmoji --help

    # Step 5: Determine version for tag
    - name: Set up release version
      id: vars
      run: |
        VERSION=$(date +'%Y%m%d%H')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # Step 6: Create a Git tag and push it to the repository
    - name: Create and push tag
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git tag v${{ env.VERSION }}
        git push origin v${{ env.VERSION }}

    # Step 7: Upload the binary to the release section
    - name: Create GitHub Release and Upload Binary
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        name: "Release v${{ env.VERSION }}"
        files: ./identmoji
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 8: Clean build artifacts
    - name: Clean build artifacts
      run: make clean
