name: Idenmoji Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allow manually triggering the workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4

    # Step 2: Install dependencies (e.g., OpenSSL)
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev

    # Step 3: Compile the binary using Makefile
    - name: Build with make
      run: make

    # Step 4: Run a basic test (replace this with actual tests if available)
    - name: Test the binary
      run: ./identmoji --help

    # Step 5: Upload the binary to the release section
    - name: Upload binary to release
      id: upload-release
      uses: softprops/action-gh-release@v1
      with:
        files: ./identmoji
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 6: Clean up the build artifacts
    - name: Clean build artifacts
      run: make clean
